### PR TITLE
Simplify core logic and support BSD

### PR DESCRIPTION
**Pull request by janosgyerik**
The improvements:

- simplified the core logic (`newpwd`)
- replaced the `sed` used by `-si` with `perl`, to make it work in BSD too (dropped the special note about BSD)
- renamed `OLDPWD` to `oldpwd`, to avoid messing with the *real* `OLDPWD` automatically set by the shell when you change directories

### CODE REVIEW

**Comment by janosgyerik** [comment]
I added a test case for `/tmp/a/b/c/d/a/b` -> `/tmp/a/b/c/d/a` to reveal the bug you found, and then fixed it.

**Comment by janosgyerik** [comment]
I guess I can just sit back, you'll merge this sometime around early 2017 ;-)

**Comment by janosgyerik** [comment]
Ping. Is there an issue with this pull request?

**Comment by vigneshwaranr** [comment]
I accepted your pull request. Thanks!

There was a minor issue. You had fixed only the 3rd case (without arguments -s or -si). I put the `.*` back into the other two cases which solved the issue.

Also the test cases currently test only the 3rd case. Need to support running tests for the other two cases as well. Will do it when I get time.

Have a nice day!

**Pull request merged**
